package com.gvera.gverabot;

public enum UserState {
    REGISTER,
    REGISTER_STORE,
    STORE_DETAILS,
    CONFIRM,
    STORES,
    CANCEL,
    MENU,
    SET_DISCOUNT_MENU,
    UPDATE_ITEM_MENU,
    UPDATE_ITEM_FIELD_MENU,
    UPDATE_ITEM_FIELD_PRICE,
    UPDATE_ITEM_FIELD_QUANTITY,
    UPDATE_ITEM_FIELD_NAME,
    SET_DISCOUNT,
    ITEMS,
    ADD_ITEM,
    UPDATE_ITEM, ADD_ITEM_PRICE, ADD_ITEM_QUANTITY, ADD_ITEM_CONFIRM,
}
